fix: ensure `x-api-key` is populated in oai spec & docs
amp-labs/openapi pull request #45
Opened 2024-08-21 09:40 UTC by jatinsandilya

Api reference pages in docs now show api headers correctly:

<img width="1294" alt="Screenshot 2024-08-21 at 3 05 36 PM" src="https://github.com/user-attachments/assets/717628dd-a37e-4b13-9ab9-855594aa707f">

2024-08-21 12:02 UTC, RajatPawar requested changes
The following endpoints don't require authentication, so you will have to override their scheme to be empty - `GET /oauth-connect`, `GET /providers`, `GET /providers/:provider`, while `GET /my-info` & `POST /invites:accept` require a session token. I am not sure if it makes to have these in the API reference since that is the case.

2024-08-21 14:46 UTC, jatinsandilya commented
> The following endpoints don't require authentication, so you will have to override their scheme to be empty - `GET /oauth-connect`, `GET /providers`, `GET /providers/:provider`, while `GET /my-info` & `POST /invites:accept` require a session token. I am not sure if it makes to have these in the API reference since that is the case.
> 

Thanks for pointing out! I've fixed these. 

> Also, is there a way to modify `Authorizations` to be `Authorization`? IMO since there's just one method, it would be much nicer to have it that way!

Unfortunately not, this is how mintlify renders the openapi spec and we dont have control over it :/

2024-08-22 04:49 UTC, laurenzlong commented
@RajatPawar @jatinsandilya FYI, GetProvider and ListProviders do require authentication (but any API key will, there isn't an an `authorizeProjectResources` check. Only endpoints that have `Insecure: true` in the server's routes/route.go file are truly public.

2024-08-22 04:49 UTC, laurenzlong approved these changes

2024-08-22 04:49 UTC, merged

2024-08-22 08:38 UTC, RajatPawar commented
> @RajatPawar @jatinsandilya FYI, GetProvider and ListProviders do require authentication (but any API key will, there isn't an an `authorizeProjectResources` check. Only endpoints that have `Insecure: true` in the server's routes/route.go file are truly public.

My bad, I called the API without a key but my active clerk session must let me in, thanks for catching this!